- topic: /color/camera_info
  tunnel_queue_size: 
  server_namespace: 

- topic: /color/image
  tunnel_queue_size: 
  server_namespace: 

- topic: /image/compressed
  tunnel_queue_size: 
  server_namespace: 

- topic: /image/compressedDepth
  tunnel_queue_size: 
  server_namespace: 

- topic: /image/theora
  tunnel_queue_size: 
  server_namespace: 

- topic: /imu
  tunnel_queue_size: 
  server_namespace: 

- topic: /joint_states
  tunnel_queue_size: 
  server_namespace: 

- topic: /left/camera_info
  tunnel_queue_size: 
  server_namespace: 

- topic: /left/image_rect
  tunnel_queue_size: 
  server_namespace: 

- topic: /left/image_rect/compressed
  tunnel_queue_size: 
  server_namespace: 

- topic: /left/image_rect/compressedDepth
  tunnel_queue_size: 
  server_namespace: 

- topic: /left/image_rect/theora
  tunnel_queue_size: 
  server_namespace: 

- topic: /right/camera_info
  tunnel_queue_size: 
  server_namespace: 

- topic: /right/image_rect
  tunnel_queue_size: 
  server_namespace: 

- topic: /right/image_rect/compressed
  tunnel_queue_size: 
  server_namespace: 

- topic: /right/image_rect/compressedDepth
  tunnel_queue_size: 
  server_namespace: 

- topic: /right/image_rect/theora
  tunnel_queue_size: 
  server_namespace: 

- topic: /stereo/camera_info
  tunnel_queue_size: 
  server_namespace: 

- topic: /stereo/converted_depth
  tunnel_queue_size: 
  server_namespace: 

- topic: /stereo/depth
  tunnel_queue_size: 
  server_namespace: 

- topic: /stereo/depth/compressed
  tunnel_queue_size: 
  server_namespace: 

- topic: /stereo/depth/compressedDepth
  tunnel_queue_size: 
  server_namespace: 

- topic: /stereo/depth/theora
  tunnel_queue_size: 
  server_namespace: 

- topic: /stereo/points
  tunnel_queue_size: 
  server_namespace: 

- topic: /tf
  tunnel_queue_size: 
  server_namespace: 
